#!/usr/bin/env python3
"""Embeds the TTF files in src/fonts/ as byte arrays into src/fonts.generated.h.

Run automatically by CMake (see CMakeLists.txt) before compiling; the raw .ttf
files are the checked-in source of truth, the header is a gitignored build
artifact.
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
FONTS_DIR = os.path.join(ROOT, "src", "fonts")
OUT_PATH = os.path.join(ROOT, "src", "fonts.generated.h")

# (source file, C identifier prefix, human-readable name, license note)
FONTS = [
    ("PTSerif-Regular.ttf", "PTSerifRegular", "PT Serif Regular",
     "SIL Open Font License 1.1 - https://github.com/google/fonts/tree/main/ofl/ptserif"),
]


def emit_array(f, ident, data):
    f.write(f"inline constexpr unsigned char k{ident}TTF[] = {{\n")
    for i in range(0, len(data), 20):
        chunk = data[i:i + 20]
        f.write("    " + ", ".join(str(b) for b in chunk) + ",\n")
    f.write("};\n")
    f.write(f"inline constexpr unsigned int k{ident}TTFSize = sizeof(k{ident}TTF);\n\n")


def main():
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/gen-fonts.py from the TTFs in src/fonts/. Do not edit",
        "// by hand or commit this file directly - it is rebuilt on every CMake configure.",
        "// Sources (SIL Open Font License 1.1):",
    ]
    for _, _, name, license_note in FONTS:
        lines.append(f"//   {name}: {license_note}")
    lines.append("")
    lines.append("namespace nocturne {")
    lines.append("")

    with open(OUT_PATH, "w", newline="\n") as out:
        out.write("\n".join(lines) + "\n")
        for filename, ident, _, _ in FONTS:
            with open(os.path.join(FONTS_DIR, filename), "rb") as fin:
                data = fin.read()
            emit_array(out, ident, data)
        out.write("}  // namespace nocturne\n")

    print(f"+ wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
